version: "3.8"

services:
  app:
    image: app
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: coords
